language: php
php:
  - '5.5.9'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'

install:
  - export COMPOSER_HOME=$(pwd)/.composer_home
  - export COMPOSER_CACHE=$(pwd)/.composer_cache
  - mkdir -p COMPOSER_HOME COMPOSER_CACHE
  - rm composer.lock
  - composer global require --no-progress --no-suggest --no-interaction --prefer-dist "phpunit/phpunit:^4.8" "behat/behat:3.*" friendsofphp/php-cs-fixer
  - composer install --no-dev --no-progress --no-suggest --no-interaction --prefer-dist
  - composer dump -o -a --no-interaction

script:
  - ${COMPOSER_HOME}/vendor/bin/phpunit
  - ${COMPOSER_HOME}/vendor/bin/behat
  - ${COMPOSER_HOME}/vendor/bin/php-cs-fixer fix --dry-run --using-cache=no -v

cache:
  directories:
  - vendor
  - .composer_home
  - .composer_cache
