language: php
php:
  - '5.6'
  - '5.5'
  - '5.5.9'
  - '5.4'
  - '7.0'
  - hhvm
  - nightly
script: vendor/bin/phing ci
install:
  - rm composer.lock
  - composer install
cache:
  directories:
  - vendor
